language: go
sudo: false
go:
- '1.11'
before_script:
- bash scripts/gogetcookie.sh
- go get ./...
script:
- make fmtcheck
- make vet
branches:
  only:
  - wizzie
  - custom
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_deploy:
- make targets
deploy:
  provider: releases
  api_key:
    secure: hmL3hRUB5Jy+xDcDiTNmUam/KsQ7mjBScrz/P1oltOB1lhd/cMAdrEGZm3uzjn2eeZKX+YR2sJBJ9Alzb9qU4soKvkmvelfP7iUnH0yoj9wAEFwvpsShL4VhqtyBMYE7ng826cI4ITEO70Tabq6e4dUKzkaf1uPuqlRhCUebOZZRr9KjJl0YdAl5QPImF31oef0DwXedoVqn0GljTInFJYZ8+OfhYmvcEg6fwre8hlUg8svxDwvAaT5cfNF6F13PqhzsmorJyhsnGCuF+BmgRVaCtlEpyJoonobMMPluepne09lj2qP7efCcJqJYziL9hVV8diZ4jnPeWxXGIipNsp+uVHf3kmyoUqumczSOqWcfTvo96G99kva/o4y9yZjyHvT+PNBi4JnHrvJ3aQqRIKj/XFWHN4PaWX41Qiyg/qAiFsFvLNsf0tZH1BN9HtzXSJ4JCdbkv0t+QKnZqFvM8kM1rhZyonlG3AEzWXi4NxStlEgT2KbTyC2wIubVs9ytIATnVR8A9uKm7Mu1Uoefdw4nSNDNWRxjFkFBjY43tmREdhJojESBGHoC+zdxE05S2wkgj66nPtAD1SRGJepdUADUSzWausFiVqlJnHu61DfVnnY+Yay48M/e7/Aq+F9yYU3O8E5mLOI8JrvxlTEIrwqwPj+qy9BAPyH4tdkENq8=
  file: dist/*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: wizzie-io/terraform-provider-kubernetes
    tags: true
    branch: wizzie
